name: ci
on: [push, pull_request]
jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: pip install -U pip coveralls
      - name: build native code
        run: make build
      - name: Run tests!
        run: |
          ulimit -c unlimited
          sudo $(which python3) -m coverage run -m unittest discover -s tests/
      - name: Log coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
      - name: is there a core dump?
        if: ${{ failure() }}
        run: ls -lR /cores
